// Tiered word bank for survival mode
// Tier 1: 3-4 chars  Tier 2: 5-6 chars  Tier 3: 7-9 chars  Tier 4: 10+ chars

export const WORDS_T1 = [
  'the','and','for','are','but','not','you','all','can','was','one','our',
  'out','day','get','has','how','man','new','now','old','see','two','who',
  'boy','did','its','let','put','say','she','too','use','job','low','own',
  'run','set','sun','try','win','yes','age','air','art','big','bit','buy',
  'car','cut','dog','eat','end','eye','far','few','fit','fix','fly','fun',
  'got','hot','ice','key','kid','law','lay','leg','map','may','met','mix',
  'net','oil','pay','per','pot','raw','red','row','sir','six','sky','tax',
  'tie','tip','ton','via','war','wet','aim','arc','arm','ash','ask','bay',
  'bed','bow','box','cab','cap','cup','dam','due','dug','dye','eel','egg',
  'elf','elm','era','eve','ewe','fad','fan','fat','fig','fin','fog','foe',
  'gem','gap','gas','gel','gin','gnu','gum','gut','gym','ham','hay','hen',
  'hip','hit','hog','hub','hue','hut','imp','ink','ion','ivy','jam','jar',
  'jaw','joy','jug','jut','keg','kin','kit','lab','lag','lap','lax','led',
  'lid','lip','log','lot','lug','mad','mat','mob','mod','mop','mud','mug',
  'nap','nod','nun','nut','oak','oar','odd','off','opt','orb','ore','owl',
  'pad','pan','paw','pea','peg','pen','pet','pie','pig','pin','pit','ply',
  'pod','pop','pow','pro','pub','pun','pup','pus','pew','rat','rib','rut',
  'rye','sap','sat','saw','sax','sea','sew','shy','sin','sip','sob','sod',
  'son','soy','spa','spy','sty','sue','sum','tab','tan','tar','tea','tin',
  'tip','toe','ton','top','toy','tug','tun','tux','urn','van','vat','vow',
  'wag','web','wig','wit','woe','wok','woo','yak','yam','yap','yew','zap',
  'zeal','zinc','zero','zone','zoom','bale','bane','bare','bark','barn',
  'base','bath','bead','beam','bean','bear','beat','beef','beer','bell',
  'belt','bird','bite','blow','blue','boar','bolt','bomb','bond','bone',
  'book','bore','born','boss','bout','brow','buff','bull','bunk','burn',
  'burp','cage','cake','calf','calm','came','cane','cape','card','care',
  'cart','case','cash','cast','cave','cell','chat','chef','chin','chip',
  'clam','clan','claw','clay','clip','club','clue','coal','coat','code',
  'coil','coin','cold','colt','cone','cook','cool','cope','cord','cork',
  'corn','cost','coup','cove','crab','crew','crop','crow','cube','curl',
  'cyst','dark','dart','dash','data','date','dawn','dead','deaf','deal',
  'dear','debt','deck','deed','deep','deer','dent','deny','desk','diet',
  'dime','dine','dip','dire','dirt','dish','disk','dock','dome','doom',
  'door','dose','dote','dove','down','drag','drip','drop','drum','dual',
  'dull','dump','dune','dusk','dust','duty','each','earn','ease','edge',
  'emit','epic','even','evil','exam','exit','face','fact','fade','fail',
  'faint','fame','farm','fast','fate','feat','feel','feet','fell','felt',
  'fend','fern','fill','film','find','fine','fire','firm','fish','fist',
  'flag','flat','flaw','flea','flew','flex','flip','flit','flow','foam',
  'fold','folk','fond','font','ford','fore','fork','form','fort','foul',
  'four','fowl','free','frog','from','fuel','full','fury','fuse','fuzz',
];

export const WORDS_T2 = [
  'about','above','after','again','agent','agree','ahead','alarm','album',
  'alert','alive','allow','alone','along','alter','among','anger','angle',
  'apart','apply','arena','argue','arise','aside','asset','avoid','award',
  'aware','awful','badly','basis','began','begin','being','below','blame',
  'bland','blank','blast','blend','blind','block','blood','blown','board',
  'bonus','brain','brand','brave','break','breed','brick','bride','brief',
  'bring','broad','broke','brown','built','burst','camel','carry','catch',
  'cause','cease','chain','chair','chaos','charm','chart','chase','cheap',
  'check','cheek','cheer','chess','chest','chief','child','claim','clash',
  'class','clean','clear','clerk','click','cliff','climb','cling','clone',
  'close','cloud','coach','coast','comet','comic','craft','crack','crash',
  'crazy','cream','crisp','cross','cruel','crush','curve','cycle','daily',
  'dance','decay','delay','depot','depth','digit','dirty','disco','dizzy',
  'donor','doubt','dough','draft','drain','drama','drank','drawn','dream',
  'dress','drift','drink','drive','drove','dryer','eagle','early','earth',
  'eight','elect','elbow','elite','empty','enemy','enjoy','enter','equal',
  'error','essay','event','every','exact','exist','extra','fable','fairy',
  'faith','false','fancy','fatal','fault','feast','field','fifth','fifty',
  'fight','final','first','fixed','flame','flash','flesh','float','flood',
  'floor','flour','flute','focus','force','forge','forty','forum','found',
  'frame','frank','fraud','fresh','front','frost','froze','fully','funny',
  'given','gland','glass','gloom','glove','going','grace','grade','grain',
  'grand','grant','grasp','grass','grave','great','green','greet','grief',
  'grill','grind','groan','gross','group','grove','growl','grown','guard',
  'guess','guest','guide','guild','guile','guilt','guise','gusto','happy',
  'harsh','heart','heavy','hence','hippo','hoist','honor','horse','hotel',
  'house','human','humor','hurry','hyena','ideal','image','imply','index',
  'infer','inner','input','irony','ivory','jaunt','jewel','joint','joker',
  'joust','judge','juice','jumbo','juror','karma','kayak','kebab','knack',
  'kneel','knife','knock','knoll','known','label','large','laser','later',
  'laugh','layer','learn','lease','least','legal','level','light','limit',
  'lingo','liver','local','lodge','logic','loose','lover','lower','lucky',
  'lunar','lunch','lusty','lying','magic','major','maple','march','marsh',
  'match','mayor','media','merge','mercy','metal','might','mirth','mixed',
  'model','money','month','moral','motor','mount','mouse','mouth','moved',
  'movie','muddy','music','naive','never','noble','noise','north','noted',
  'novel','nurse','nymph','occur','ocean','offer','often','olive','orbit',
  'order','other','outer','owned','oxide','ozone','paint','panel','panic',
  'paper','party','patch','pause','peace','pearl','penny','phase','phone',
  'photo','piano','piece','pilot','pinch','pixel','place','plain','plane',
  'plant','plate','plaza','plead','pluck','plumb','plume','plush','point',
  'poker','polar','poppy','power','press','price','pride','prime','print',
  'prize','probe','prone','proof','prose','proud','prove','prune','psych',
  'pulse','punch','pupil','queen','query','quest','queue','quick','quiet',
  'quota','quote','radar','radio','raise','rally','range','rapid','ratio',
  'reach','react','ready','realm','rebel','relax','reply','rider','right',
  'rigid','risky','risen','river','robin','robot','rocky','rouge','rough',
  'round','route','royal','rugby','ruler','rural','sadly','saint','salad',
  'sauce','scale','scene','scope','score','scout','screw','seize','sense',
  'serve','seven','shade','shake','shall','shame','share','shark','sharp',
  'sheep','sheer','shell','shift','shine','shirt','shock','shoot','shore',
  'short','shout','sight','since','sixth','sixty','skill','sleep','slice',
  'slide','slope','small','smart','smell','smile','smith','smoke','solar',
  'solid','solve','sorry','south','space','speak','spend','spice','spike',
  'spine','spite','split','spoke','spoon','spore','sport','spray','squad',
  'squat','stack','staff','stage','stake','stand','stark','start','state',
  'stave','steak','steal','steam','steel','steep','steer','stern','stick',
  'stiff','still','stock','stone','stood','storm','story','straw','strap',
  'stray','strip','strum','strut','study','stuff','stump','style','sugar',
  'suite','super','surge','swamp','swear','sweep','sweet','swept','swift',
  'swirl','sword','sworn','syrup','table','taken','taste','teach','tempo',
  'tense','tenth','terms','thank','their','there','thick','thing','think',
  'third','those','three','threw','throw','thumb','tiger','tight','timer',
  'tired','title','today','token','total','touch','tough','tower','trace',
  'track','trade','trail','trait','tramp','trash','treat','trend','trial',
  'tribe','trick','tried','troop','truly','trump','trunk','trust','truth',
  'tumor','tunic','typic','ultra','uncle','under','unify','union','unity',
  'until','upper','upset','urban','usage','usual','utter','valor','value',
  'valve','vapor','vault','venue','verse','viral','virus','visit','vista',
  'vital','vivid','vocal','vodka','voice','voter','vowel','waist','waste',
  'watch','water','weary','weave','wedge','weigh','weird','wheat','wheel',
  'where','which','while','white','whole','whose','wider','witch','woman',
  'woods','world','worry','worst','worth','would','wound','wrath','write',
  'wrong','youth','zebra','zipper',
];

export const WORDS_T3 = [
  'ability','absence','absolute','achieve','acquire','address','advance',
  'against','already','ancient','another','anxiety','applied','arrange',
  'article','attempt','attract','authors','balance','believe','benefit',
  'billion','biology','bizarre','blanket','boolean','browser','cabinet',
  'capture','careful','cavalry','century','chapter','citizen','climate',
  'collect','combine','comfort','command','compact','compare','compete',
  'concern','conduct','confirm','connect','contain','content','context',
  'control','convert','council','country','culture','curious','current',
  'cushion','declare','default','defense','deliver','digital','display',
  'distant','diverse','divided','dynamic','element','endless','enhance',
  'exclude','examine','example','execute','explain','explore','express',
  'extreme','factory','feature','foreign','formula','forward','freedom',
  'frequent','gateway','general','genetic','genuine','glimpse','glucose',
  'graphic','habitat','harmony','harvest','history','imagine','include',
  'insight','install','instead','inverse','inspire','journal','justify',
  'kingdom','knowing','language','largest','library','maximum','minimum',
  'measure','mention','mission','monster','natural','neglect','network',
  'nothing','observe','offense','opinion','optical','outcome','outside',
  'overlap','pattern','perform','perhaps','physics','possess','prevent',
  'process','product','produce','profile','program','project','promise',
  'protect','protein','provide','publish','purpose','quarter','quickly',
  'realize','receive','require','reserve','resolve','respect','restore',
  'reverse','science','segment','service','setting','similar','society',
  'soldier','someone','storage','subject','success','support','surface',
  'survive','trigger','upgrade','version','village','virtual','visible',
];

export const WORDS_T4 = [
  'accomplish','achievement','additional','algorithms','alternative',
  'ambitious','appearance','application','atmosphere','capability',
  'championship','collection','comfortable','competition','complexity',
  'compressed','contribute','creativity','description','destination',
  'development','difference','environment','estimation','everything',
  'explanation','foundation','frequently','fulfillment','immediately',
  'improvement','information','innovative','integration','intelligence',
  'interaction','interesting','mathematics','measurement','opportunity',
  'overarching','partnership','performance','photography','programming',
  'replacement','requirement','responsible','restriction','revolution',
  'scholarship','spectacular','substantial','temperature','traditional',
  'transmission','transparent','tremendous','unexpected','unfortunately',
  'universally','verification','willingness','wonderfully',
];

export const ALL_WORDS = [...WORDS_T1, ...WORDS_T2, ...WORDS_T3, ...WORDS_T4];

export function wordsByTier(tier: 1 | 2 | 3 | 4): string[] {
  if (tier === 1) return WORDS_T1;
  if (tier === 2) return WORDS_T2;
  if (tier === 3) return WORDS_T3;
  return WORDS_T4;
}
